export const initialGoal = {
  title: "完成 Anchor 产品宣传片",
  note: "今天完成 60 秒成片：先定脚本与分镜，再生成镜头，最后由我完成节奏和审美判断。",
  startedAt: "14:10",
};

export const initialTasks = [
  {
    id: "script",
    app: "Claude",
    appCode: "C",
    appTone: "coral",
    visual: "wave",
    metric: "58s",
    metricLabel: "目标时长",
    title: "打磨第三幕脚本",
    status: "running",
    statusLabel: "生成中",
    progress: 64,
    detail: "正在压缩第三幕旁白，并统一产品语气",
    eta: "约 7 分钟",
    updated: "刚刚",
    activity: ["完成开场冲突", "合并两版产品叙事", "正在重写第三幕旁白"],
  },
  {
    id: "storyboard",
    app: "Gemini",
    appCode: "G",
    appTone: "blue",
    visual: "frames",
    metric: "12",
    metricLabel: "候选分镜",
    title: "确认故事分镜",
    status: "attention",
    statusLabel: "等你确认",
    progress: 82,
    detail: "12 张候选分镜已生成，需要选择视觉方向",
    eta: "需要你的判断",
    updated: "2 分钟前",
    activity: ["生成 3 套构图方向", "完成 12 张分镜", "等待选择主视觉方向"],
  },
  {
    id: "render",
    app: "Seedance",
    appCode: "S",
    appTone: "cyan",
    visual: "orbit",
    metric: "04/10",
    metricLabel: "当前镜头",
    title: "生成转场镜头",
    status: "running",
    statusLabel: "渲染中",
    progress: 37,
    detail: "镜头 04 / 10 正在渲染，运动稳定性良好",
    eta: "约 18 分钟",
    updated: "刚刚",
    activity: ["上传分镜与提示词", "完成前三个镜头", "正在渲染镜头 04"],
  },
  {
    id: "edit",
    app: "Final Cut",
    appCode: "F",
    appTone: "ink",
    visual: "timeline",
    metric: "60s",
    metricLabel: "剪辑时间线",
    title: "完成节奏剪辑",
    status: "queued",
    statusLabel: "准备中",
    progress: 18,
    detail: "素材工程已建立，等待分镜确认后继续",
    eta: "前置任务未完成",
    updated: "5 分钟前",
    activity: ["建立 60 秒时间线", "导入现有素材", "等待确认分镜"],
  },
];

export const returnChanges = [
  { time: "14:34", title: "Gemini 完成 12 张分镜", detail: "3 套视觉方向等待判断", tone: "attention" },
  { time: "14:38", title: "Seedance 完成第 3 个镜头", detail: "运动稳定性检查通过", tone: "success" },
  { time: "14:41", title: "Claude 将脚本压缩至 58 秒", detail: "旁白已达到成片目标", tone: "ai" },
];

export const notifications = [
  { id: 1, app: "Gemini", taskId: "storyboard", title: "分镜已准备好", body: "有 3 套方向等待你的审美判断。", time: "2 分钟前", unread: true },
  { id: 2, app: "Seedance", taskId: "render", title: "镜头 03 渲染完成", body: "运动稳定性检查通过。", time: "6 分钟前", unread: true },
  { id: 3, app: "Anchor", taskId: null, title: "上下文已保存", body: "本次工作的目标与状态已同步。", time: "28 分钟前", unread: false },
];
