#if os(iOS)
import AnchorDesign

/// Copy stays in the shared string catalog alongside the rest of the app.
enum SetupCopy {
    static let title = AnchorStrings.value("setup.plan.title", default: "Task anchoring")
    static let subtitle = AnchorStrings.value("setup.plan.subtitle", default: "Turn your thoughts into a plan")
    static let reviewSubtitle = AnchorStrings.value("setup.plan.review.subtitle", default: "Your words, ready for a final review")
    static let goal = AnchorStrings.value("setup.plan.goal", default: "Goal")
    static let criteria = AnchorStrings.value("setup.plan.criteria", default: "Completion criteria")
    static let steps = AnchorStrings.value("setup.plan.steps", default: "Action plan")
    static let goalPrompt = AnchorStrings.value("setup.plan.goal.prompt", default: "What would you like to do?")
    static let criteriaPrompt = AnchorStrings.value("setup.plan.criteria.prompt", default: "What will done look like?")
    static let stepsPrompt = AnchorStrings.value("setup.plan.steps.prompt", default: "How will you get there?")
    static let goalPlaceholder = AnchorStrings.value("setup.plan.goal.placeholder", default: "Start with a goal, a question, or an idea…")
    static let criteriaPlaceholder = AnchorStrings.value("setup.plan.criteria.placeholder", default: "Write each completion criterion on a new line…")
    static let stepsPlaceholder = AnchorStrings.value("setup.plan.steps.placeholder", default: "Write each action step on a new line…")
    static let goalHint = AnchorStrings.value("setup.plan.goal.hint", default: "For example: finish redesigning the Anchor homepage")
    static let criteriaHint = AnchorStrings.value("setup.plan.criteria.hint", default: "For example: clear hierarchy, a working prototype. Put each criterion on a new line.")
    static let stepsHint = AnchorStrings.value("setup.plan.steps.hint", default: "For example: review the content, sketch the layout, build the prototype. Put each step on a new line.")
    static let hintTitle = AnchorStrings.value("setup.plan.hint.title", default: "Try describing it like this")
    static let next = AnchorStrings.value("setup.plan.next", default: "Next")
    static let review = AnchorStrings.value("setup.plan.review", default: "Review plan")
    static let original = AnchorStrings.value("setup.plan.original", default: "Your description")
    static let edit = AnchorStrings.value("setup.plan.edit", default: "Edit")
    static let back = AnchorStrings.value("setup.plan.back", default: "Back")
    static let start = AnchorStrings.value("setup.plan.start", default: "Start")
    static let saving = AnchorStrings.value("setup.plan.saving", default: "Saving…")
    static let saveFailed = AnchorStrings.value("setup.plan.save.failed", default: "Could not save this task. Your input is still here. Please try again.")
    static let photos = AnchorStrings.value("setup.plan.photos", default: "Add images")
    static let removePhoto = AnchorStrings.value("setup.plan.photo.remove", default: "Remove image")
    static let photo = AnchorStrings.value("setup.plan.photo", default: "Reference image")
    static let photoFailed = AnchorStrings.value("setup.plan.photo.failed", default: "An image could not be added. Try choosing it again.")
    static let keyboard = AnchorStrings.value("setup.plan.keyboard", default: "Use keyboard")
    static let newLine = AnchorStrings.value("setup.plan.newline", default: "New line")
    static let addCriterion = AnchorStrings.value("setup.plan.criterion.add", default: "Add a criterion")
    static let addStep = AnchorStrings.value("setup.plan.step.add", default: "Add a step")
    static let reorder = AnchorStrings.value("setup.plan.reorder", default: "Reorder step")
    static let up = AnchorStrings.value("setup.plan.up", default: "Move up")
    static let down = AnchorStrings.value("setup.plan.down", default: "Move down")
    static let doneEditing = AnchorStrings.value("setup.plan.edit.done", default: "Done editing")
    static let inputRequired = AnchorStrings.value("setup.plan.required", default: "Write or say a few words to continue")

}
#endif
